import Link from 'next/link'

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-white py-12">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-12">
          <h1 className="text-4xl sm:text-5xl font-bold text-rgs-black mb-4">
            Privacy Policy
          </h1>
          <p className="text-gray-600">Last updated: July 20, 2025</p>
        </div>

        {/* Content */}
        <div className="prose prose-lg max-w-none">
          <p className="text-gray-700 leading-relaxed mb-6">
            This Privacy Policy describes Our policies and procedures on the collection, use and 
            disclosure of Your information when You use the Service and tells You about Your privacy 
            rights and how the law protects You.
          </p>

          <p className="text-gray-700 leading-relaxed mb-8">
            We use Your Personal data to provide and improve the Service. By using the Service, You 
            agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          {/* Interpretation and Definitions */}
          <section className="mb-12">
            <h2 className="text-3xl font-bold text-rgs-black mb-6">
              Interpretation and Definitions
            </h2>

            <h3 className="text-2xl font-bold text-rgs-black mb-4">Interpretation</h3>
            <p className="text-gray-700 leading-relaxed mb-6">
              The words of which the initial letter is capitalized have meanings defined under the 
              following conditions. The following definitions shall have the same meaning regardless 
              of whether they appear in singular or in plural.
            </p>

            <h3 className="text-2xl font-bold text-rgs-black mb-4">Definitions</h3>
            <p className="text-gray-700 leading-relaxed mb-4">
              For the purposes of this Privacy Policy:
            </p>

            <ul className="list-disc pl-6 space-y-3 text-gray-700 mb-6">
              <li>
                <strong>Account</strong> means a unique account created for You to access our Service 
                or parts of our Service.
              </li>
              <li>
                <strong>Affiliate</strong> means an entity that controls, is controlled by or is under 
                common control with a party, where "control" means ownership of 50% or more of the shares, 
                equity interest or other securities entitled to vote for election of directors or other 
                managing authority.
              </li>
              <li>
                <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in 
                this Agreement) refers to The Rich Grad Student LLC, Delaware 19958, Sussex County.
              </li>
              <li>
                <strong>Cookies</strong> are small files that are placed on Your computer, mobile device 
                or any other device by a website, containing the details of Your browsing history on that 
                website among its many uses.
              </li>
              <li>
                <strong>Country</strong> refers to: Illinois, United States
              </li>
              <li>
                <strong>Device</strong> means any device that can access the Service such as a computer, 
                a cellphone or a digital tablet.
              </li>
              <li>
                <strong>Personal Data</strong> is any information that relates to an identified or 
                identifiable individual.
              </li>
              <li>
                <strong>Service</strong> refers to the Website.
              </li>
              <li>
                <strong>Service Provider</strong> means any natural or legal person who processes the 
                data on behalf of the Company. It refers to third-party companies or individuals employed 
                by the Company to facilitate the Service, to provide the Service on behalf of the Company, 
                to perform services related to the Service or to assist the Company in analyzing how the 
                Service is used.
              </li>
              <li>
                <strong>Usage Data</strong> refers to data collected automatically, either generated by 
                the use of the Service or from the Service infrastructure itself (for example, the duration 
                of a page visit).
              </li>
              <li>
                <strong>Website</strong> refers to The Rich Grad Student, accessible from{' '}
                <Link href="/" className="text-blue-600 hover:text-blue-800 underline">
                  therichgradstudent.com
                </Link>
              </li>
              <li>
                <strong>You</strong> means the individual accessing or using the Service, or the company, 
                or other legal entity on behalf of which such individual is accessing or using the Service, 
                as applicable.
              </li>
            </ul>
          </section>

          {/* Collecting and Using Your Personal Data */}
          <section className="mb-12">
            <h2 className="text-3xl font-bold text-rgs-black mb-6">
              Collecting and Using Your Personal Data
            </h2>

            <h3 className="text-2xl font-bold text-rgs-black mb-4">Types of Data Collected</h3>

            <h4 className="text-xl font-bold text-rgs-black mb-3">Personal Data</h4>
            <p className="text-gray-700 leading-relaxed mb-6">
              While using Our Service, We may ask You to provide Us with certain personally identifiable 
              information that can be used to contact or identify You. Personally identifiable information 
              may include, but is not limited to Usage Data.
            </p>

            <h4 className="text-xl font-bold text-rgs-black mb-3">Usage Data</h4>
            <p className="text-gray-700 leading-relaxed mb-4">
              Usage Data is collected automatically when using the Service.
            </p>
            <p className="text-gray-700 leading-relaxed mb-4">
              Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), 
              browser type, browser version, the pages of our Service that You visit, the time and date of Your 
              visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>
            <p className="text-gray-700 leading-relaxed mb-6">
              When You access the Service by or through a mobile device, We may collect certain information 
              automatically, including, but not limited to, the type of mobile device You use, Your mobile 
              device unique ID, the IP address of Your mobile device, Your mobile operating system, the type 
              of mobile Internet browser You use, unique device identifiers and other diagnostic data.
            </p>
          </section>

          {/* Tracking Technologies and Cookies */}
          <section className="mb-12">
            <h3 className="text-2xl font-bold text-rgs-black mb-4">
              Tracking Technologies and Cookies
            </h3>
            <p className="text-gray-700 leading-relaxed mb-4">
              We use Cookies and similar tracking technologies to track the activity on Our Service and 
              store certain information. Tracking technologies used are beacons, tags, and scripts to collect 
              and track information and to improve and analyze Our Service.
            </p>

            <h4 className="text-xl font-bold text-rgs-black mb-3">Types of Cookies We Use</h4>
            <ul className="list-disc pl-6 space-y-3 text-gray-700 mb-6">
              <li>
                <strong>Necessary / Essential Cookies:</strong> These Cookies are essential to provide You 
                with services available through the Website and to enable You to use some of its features.
              </li>
              <li>
                <strong>Cookies Policy / Notice Acceptance Cookies:</strong> These Cookies identify if users 
                have accepted the use of cookies on the Website.
              </li>
              <li>
                <strong>Functionality Cookies:</strong> These Cookies allow us to remember choices You make 
                when You use the Website, such as remembering your login details or language preference.
              </li>
            </ul>
          </section>

          {/* Use of Your Personal Data */}
          <section className="mb-12">
            <h3 className="text-2xl font-bold text-rgs-black mb-4">
              Use of Your Personal Data
            </h3>
            <p className="text-gray-700 leading-relaxed mb-4">
              The Company may use Personal Data for the following purposes:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
              <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
              <li>To manage Your Account and registration as a user of the Service.</li>
              <li>For the performance of a contract for products, items or services You have purchased.</li>
              <li>To contact You by email or other forms of electronic communication.</li>
              <li>To provide You with news, special offers and general information.</li>
              <li>To manage Your requests to Us.</li>
              <li>For business transfers and other purposes such as data analysis.</li>
            </ul>
          </section>

          {/* Retention of Your Personal Data */}
          <section className="mb-12">
            <h3 className="text-2xl font-bold text-rgs-black mb-4">
              Retention of Your Personal Data
            </h3>
            <p className="text-gray-700 leading-relaxed mb-6">
              The Company will retain Your Personal Data only for as long as is necessary for the purposes 
              set out in this Privacy Policy. We will retain and use Your Personal Data to the extent 
              necessary to comply with our legal obligations, resolve disputes, and enforce our legal 
              agreements and policies.
            </p>
          </section>

          {/* Security of Your Personal Data */}
          <section className="mb-12">
            <h3 className="text-2xl font-bold text-rgs-black mb-4">
              Security of Your Personal Data
            </h3>
            <p className="text-gray-700 leading-relaxed mb-6">
              The security of Your Personal Data is important to Us, but remember that no method of 
              transmission over the Internet, or method of electronic storage is 100% secure. While We 
              strive to use commercially acceptable means to protect Your Personal Data, We cannot 
              guarantee its absolute security.
            </p>
          </section>

          {/* Children's Privacy */}
          <section className="mb-12">
            <h3 className="text-2xl font-bold text-rgs-black mb-4">
              Children's Privacy
            </h3>
            <p className="text-gray-700 leading-relaxed mb-6">
              Our Service does not address anyone under the age of 13. We do not knowingly collect 
              personally identifiable information from anyone under the age of 13. If You are a parent 
              or guardian and You are aware that Your child has provided Us with Personal Data, please 
              contact Us.
            </p>
          </section>

          {/* Links to Other Websites */}
          <section className="mb-12">
            <h3 className="text-2xl font-bold text-rgs-black mb-4">
              Links to Other Websites
            </h3>
            <p className="text-gray-700 leading-relaxed mb-6">
              Our Service may contain links to other websites that are not operated by Us. If You click 
              on a third party link, You will be directed to that third party's site. We strongly advise 
              You to review the Privacy Policy of every site You visit.
            </p>
          </section>

          {/* Changes to this Privacy Policy */}
          <section className="mb-12">
            <h3 className="text-2xl font-bold text-rgs-black mb-4">
              Changes to this Privacy Policy
            </h3>
            <p className="text-gray-700 leading-relaxed mb-4">
              We may update Our Privacy Policy from time to time. We will notify You of any changes by 
              posting the new Privacy Policy on this page.
            </p>
            <p className="text-gray-700 leading-relaxed mb-6">
              You are advised to review this Privacy Policy periodically for any changes. Changes to this 
              Privacy Policy are effective when they are posted on this page.
            </p>
          </section>

          {/* Contact Us */}
          <section className="mb-12">
            <h3 className="text-2xl font-bold text-rgs-black mb-4">
              Contact Us
            </h3>
            <p className="text-gray-700 leading-relaxed mb-2">
              If you have any questions about this Privacy Policy, You can contact us:
            </p>
            <p className="text-gray-700 leading-relaxed">
              By email:{' '}
              <a 
                href="mailto:privacy@therichgradstudent.com" 
                className="text-blue-600 hover:text-blue-800 underline"
              >
                privacy@therichgradstudent.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
